version: "3"
services:
  db:
    #image: postgres:10
    build:
      context: ./api/dockerConfig
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432"
  api:
    build: ./api
    environment:
      PORT: 3001
      BASE_URL: "http://localhost"
      DB_NAME: "tubesoft"
      PSQL_PASS: "postgres"
      DB_HOST: db
    ports:
      - "8080:3001"
    volumes:
      - ./api/routes:/api/routes
      - ./api/db/models:/api/models
    depends_on:
      - db
  # client:
  #   build: ./src
  #   env_file: ./client/.env
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./client/public:/app/public
  #     - ./client/src:/app/src
  tubesoft:
    build: ./
    env_file: ./src/.env
    volumes:
      - ./src:/src
      #- ../public:/app
    ports:
      - "3000:3000"
