version: "3.3"

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: api/dockerConfig/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tubesoft
    ports:
      - "5432"
    volumes:
      - tubesoft:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      BASE_URL: "http://localhost"
      DB_NAME: tubesoft
      PSQL_USER: postgres
      PSQL_PASS: postgres
      DB_HOST: localhost
    ports:
      - "8080:3001"
    volumes:
      - ./api/routes:/api/routes
      - ./api/db/models:/api/models

    depends_on:
      - postgres

  client:
    build: ./
    env_file: ./src/.env
    volumes:
      - ./:/src
      #- ../public:/app
    ports:
      - "3000:3000"

volumes:
  tubesoft:
# version: "3.7"
# services:
#   postgres:
#     image: postgres:10.5
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     logging:
#       options:
#         max-size: 10m
#         max-file: "3"
#     ports:
#       - "5438:5432"
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#       # copy the sql script to create tables
#       - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
# version: "3"
# services:
#   postgres:
#     image: postgres:10.5
#     restart: always
#     environment:
#       # POSTGRES_USER=postgres
#       # POSTGRES_PASSWORD=postgres
#       # POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       ports:
#         - "5438:5432"
#       volumes:
#         - ./testDocker.sql:/docker-entry-pointinitdb.db/testDocker.sql

# api:
#   build: ./api
#   environment:
#     PORT: 3001
#     BASE_URL: "http://localhost"
#     DB_NAME: "tubesoft"
#     PSQL_PASS: "postgres"
#     DB_HOST: db
#   ports:
#     - "8080:3001"
#   volumes:
#     - ./api/routes:/api/routes
#     - ./api/db/models:/api/models
#   depends_on:
#     - db

# db:
#   #image: postgres:10
#   build:
#     context: ./api/dockerConfig
#   restart: always
#   environment:
#     POSTGRES_PASSWORD: "postgres"
#   ports:
#     - "5432"
# api:
#   build: ./api
#   environment:
#     PORT: 3001
#     BASE_URL: "http://localhost"
#     DB_NAME: "tubesoft"
#     PSQL_PASS: "postgres"
#     DB_HOST: db
#   ports:
#     - "8080:3001"
#   volumes:
#     - ./api/routes:/api/routes
#     - ./api/db/models:/api/models
#   depends_on:
#     - db
# # client:
# #   build: ./src
# #   env_file: ./client/.env
# #   ports:
# #     - "80:80"
# #   volumes:
# #     - ./client/public:/app/public
# #     - ./client/src:/app/src

